name: CI

on:
  push:
    branches:
      - main # ✅ Runs when pushing to main
  pull_request: # ✅ Runs for any PR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: . # ✅ Ensures repo is checked out into root folder

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # ✅ Only publish on push, not PRs
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: . # ✅ Ensures repo is checked out into root folder

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          scope: '@devprakashduve'

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install # ✅ Ensures all dependencies are available before checking for `next`

      - name: Check installed packages
        run: npm list next

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # (if applicable)

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
