name: Release & Publish to GitHub and npm

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm test # Add tests if applicable
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.action == 'published'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Bump Version (GitHub Packages)
        run: npm version patch --no-git-tag-version

      - name: Publish to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.action == 'published'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Authenticate with npmjs.com
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Bump Version (npm)
        run: npm version patch --no-git-tag-version

      - name: Publish to npmjs.com
        run: npm  publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
